[assembly: System.Reflection.AssemblyTitle("Весьмой калькулятор")]
[assembly: System.Reflection.AssemblyDescription("Wholemy.Calculator")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("Wholemy")]
[assembly: System.Reflection.AssemblyProduct("Wholemy.Calculator")]
[assembly: System.Reflection.AssemblyCopyright("Wholemy")]
[assembly: System.Reflection.AssemblyTrademark("Wholemy")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyVersion("2025.1024.2329.18")]
[assembly: System.Reflection.AssemblyFileVersion("2025.1024.2329.18")]